# Unique Key & Null Values

There are 4 tables, Sales, Customers, Items and Companies.

Sales:

Purchase_number      |Date_of_purchase      |Customer_id      |Item_code
---                  |---                   |---              |---
1                    |03/09/2016            |1                |A_1
2                    |02/12/2016            |2                |C_1
3                    |15/04/2017            |3                |D_1
4                    |24/05/2017            |1                |B_2
5                    |25/05/2017            |4                |B_2
6                    |06/06/2017            |2                |B_1
7                    |10/06/2017            |4                |A_2
8                    |13/06/2017            |3                |C_1
9                    |20/07/2017            |1                |A_1
10                   |11/08/2017            |2                |B_1

Customers:

Customer_id      |First_name    |Last_name    |Email_address                       |Number_of_complaints
---              |---           |---          |---                                 |---
1                |John          |McKinley     |john.mackinley@365careers.com       |0
2                |Elizabeth     |McFarlane    |e.mcfarlane@365careers.com          |2
3                |Kevin         |Lawrence     |kevin.lawrence@365careers.com       |1
4                |Catherine     |Winnfield    |c.winnfield@365careers.com          |0

Items:

Item_code     |Item          |Unit_price   |Company_id  |Company   |Headquarters_phone_number
---           |---           |---          |---         |---       |---
A_1           |Lamp          |20           |1           |Company A |+1(202)555-0169
A_2           |Desk          |250          |1           |Company A |+1(202)555-0169
B_1           |Lamp          |30           |2           |Company B |+1(202)555-0152
B_2           |Desk          |350          |2           |Company B |+1(202)555-0152
C_1           |Chair         |150          |3           |Company C |+1(229)853-9913
D_1           |Loudspeakers  |400          |4           |Company D |+1(618)369-7392

Companies:

Company     |Headquarters_phone_number       |Company_id
---         |---                             |---
Company A   |+1(202)555-0169                 |1
Company B   |+1(202)555-0152                 |2
Company C   |+1(229)853-9913                 |3
Company D   |+1(618)369-7392                 |4

___

In the Companies, the Company_id is a primary key in it, on the other hand you can rarely have two or more companies with the same name but it's not impossible especially if they are in a different state or if they operate in different industries, and it can not have two US numbers that are completely identical, therefore we can conclude that the values in this field have to be unique.

The Headquarters_phone_number is a unique key, they are used whenever you would like to specify that you don't want to see duplicate data in a given field.

There is one substantial difference between unique key and primary key, the unique key can contain null values, meaning if we don't know the Company D's Headquarters_phone_number, we can still have this record in the table will be functioning as part of their relational database, in addition, a table can have 0, 1, 2 or more unique keys, this means that depending on the requirements of the database, a table may or may not contain one or more unique key columns, this is different with respect to the characteristics of the primary key constraint, because the primary key can have only one per table.

Furthermore, both primary key and unique key can be applied to multiple columns not just a single column, in other words, the unique key constraint can be defined by a single field from the table it is applied to, or it could comprise a few of the columns in that table.

___

Sales|
---|
**Purchas_number**|
Date_of_purchase|
Customer_id(FK)|
Item_code(FK)|

Customers|
---|
**Customer_id**|
First_name|
Last_name|
Email_address|
Number_of_complaints|

Items|
---|
**Item_code**|
Item|
Unit_price|
Company_id(FK)|
Company|
Headquarters_phone_number|

Companies|
---|
**Company_id**|
Company|
Headquarters_phone_number|